name: Build and Deploy with Buildpacks

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Desired name for the Docker image'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ["go/mod", "go/no-imports", "nodejs/angular-npm", "nodejs/no-package-manager", "nodejs/npm", "nodejs/react-yarn", "nodejs/vue-npm", "nodejs/yarn"]
    steps:
    - name: Set directory input
      id: set_directory
      run: echo "DIRECTORY=${{ matrix.directory }}" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        path: ${{ env.DIRECTORY }}

    - name: Install Pack CLI
      run: |
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli -y
        sudo apt-get update
        sudo apt-get install pack-cli -y

    - name: Log in to GitHub Packages Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image using Buildpacks
      run: |
        pack build ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }} --builder gcr.io/buildpacks/builder:v1 --path ${{ env.DIRECTORY }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:latest

    - name: Display Docker Image URI
      run: |
          echo "Docker Image URI: ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image_name }}:latest"; exit 0

