name: Build, Deploy, and Test with Buildpacks

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Pack CLI
      run: |
        sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
        sudo apt-get update
        sudo apt-get install pack-cli
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image using Buildpacks
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-image:latest
        pack build $IMAGE_NAME --builder naveen871/go-securepack --path .
        docker push $IMAGE_NAME
        echo "image=$IMAGE_NAME" >> $GITHUB_ENV
        echo "Docker image pushed: $IMAGE_NAME"  # Display Docker image name

    - name: Display Docker image name
      run: echo "Docker image pushed: ${{ env.image }}"
